// packages/vue/src/view/tag/PopularTagList.vue
<template>
  <span v-if="isLoading">Loading tags...</span>
  <span v-else-if="error">Error while loading tags.</span>
  <TagList v-else v-bind="listProps" />
</template>

<script>
  import { mapActions, mapState } from 'vuex';
  import { TAG } from '@/state/mutationTypes';
  import TagList from './TagList';

  export default {
    methods: {
      ...mapActions({
        loadPopularTags: TAG.LOAD_POPULAR_TAGS
      })
    },

    computed: {
      listProps() {
        return {
          tags: this.tags,
          ...this.$props
        };
      },
      ...mapState({
        tags: (state) => state.tags.tags,
        isLoading: (state) => state.tags.isLoading,
        error: (state) => state.tags.error
      })
    },

    mounted() {
      this.loadPopularTags();
    },

    components: {
      TagList
    }
  };
</script>

// packages/react/src/view/tag/PopularTagList.js
/* @flow */
import React, { Component } from 'react';
import { connect } from 'react-redux';
import {
  loadPopularTags,
  type PopularTagsState
} from '../../state/tag';
import TagList, { type Props as TagListProps } from './TagList';

type Props = TagListProps & {
  loadPopularTags: typeof loadPopularTags,
  isLoading: $PropertyType<PopularTagsState, 'isLoading'>,
  error: $PropertyType<PopularTagsState, 'error'>
};

class PopularTagList extends Component<Props> {
  componentDidMount() {
    this.props.loadPopularTags();
  }

  render() {
    const { isLoading, tags, error } = this.props;

    if(isLoading) {
      return 'Loading tags...';
    }

    if(error) {
      return 'Error while loading tags.';
    }

    return <TagList tags={ tags } {...this.props} />;
  }
}

const mapStateToProps = ({ popularTags }) => ({
  tags: popularTags.tags,
  isLoading: popularTags.isLoading,
  error: popularTags.error
});

const mapDispatchToProps = {
  loadPopularTags
};

export default connect(mapStateToProps, mapDispatchToProps)(PopularTagList);
