// packages/vue/src/view/article/Feed.vue
<template>
  <div v-if="feed.error" class="article-preview">Error while loading articles.</div>
  <div v-else-if="feed.isLoading" class="article-preview">Loading articles...</div>
  <div v-else-if="!feed.articles.length" class="article-preview">No articles are here... yet.</div>
  <div v-else>
    <ArticlePreview
      v-for="article in feed.articles"
      v-bind:article="article"
      :key="article.slug"
    />
  </div>
</template>

<script>
  import ArticlePreview from './ArticlePreview';

  export default {
    props: ['feed'],
    components: {
      ArticlePreview
    }
  };
</script>

// packages/react/src/view/article/Feed.js
/* @flow */
import React from 'react';
import type { FeedState } from '../../state/article';
import ArticlePreview from './ArticlePreview';

type Props = {
  feed: FeedState
};

const Feed = ({ feed }: Props) => {
  if(feed.error) {
    return <div className="article-preview">Error while loading articles.</div>;
  }

  if(feed.isLoading) {
    return <div className="article-preview">Loading articles...</div>;
  }

  if(!feed.articles.length) {
    return <div className="article-preview">No articles are here... yet.</div>;
  }

  return feed.articles.map((article) =>
    <ArticlePreview key={ article.slug } article={ article } />
  );
};

export default Feed;
