// packages/react/src/view/layout/Nav.js
/* @flow */
import React, { Fragment } from 'react';
import { Link, NavLink, withRouter } from 'react-router-dom';
import { connect } from 'react-redux';
import type { UserState } from '../../state/user';
import AuthorLink from '../author/AuthorLink';
import AuthorImage from '../author/AuthorImage';

type Props = {
  user: $PropertyType<UserState, 'user'>
};

const Nav = (props: Props) => (
   <nav className="navbar navbar-light">
    <div className="container">
      <Link className="navbar-brand" to="/">conduit</Link>
      <ul className="nav navbar-nav pull-xs-right">
        <li className="nav-item">
          <NavLink
            className="nav-link"
            to="/"
            exact
            activeClassName="active"
          >
            Home
          </NavLink>
        </li>
        {
          props.user && (
            <Fragment>
              <li className="nav-item">
                <NavLink
                  className="nav-link"
                  activeClassName="active"
                  to="/editor"
                  exact
                >
                  <i className="ion-compose"></i>&nbsp;New Article
                </NavLink>
              </li>
              <li className="nav-item">
                <NavLink
                  className="nav-link"
                  activeClassName="active"
                  to="/settings"
                >
                  <i className="ion-gear-a"></i>&nbsp;Settings
                </NavLink>
              </li>
              <li className="nav-item">
                <AuthorLink
                  as={ NavLink }
                  className="nav-link"
                  activeClassName="active"
                  author={ props.user }
                >
                  <AuthorImage author={ props.user } className="user-pic" />

                  { props.user.username }
                </AuthorLink>
              </li>
            </Fragment>
          )
        }
        {
          !props.user && (
            <Fragment>
              <li className="nav-item">
                <NavLink
                  className="nav-link"
                  to="/login"
                  activeClassName="active"
                >
                  Sign In
                </NavLink>
              </li>
              <li className="nav-item">
                <NavLink
                  className="nav-link"
                  to="/register"
                  activeClassName="active"
                >
                  Sign up
                </NavLink>
              </li>
            </Fragment>
          )
        }
      </ul>
    </div>
  </nav>
);

const mapStateToProps = ({ user }) => ({
  user: user.user
});

export default withRouter(connect(mapStateToProps)(Nav));

// packages/vue/src/view/layout/Nav.vue
<template>
  <nav class="navbar navbar-light">
    <div class="container">
      <a class="navbar-brand" href="index.html">conduit</a>
      <ul class="nav navbar-nav pull-xs-right">
        <li class="nav-item">
          <!-- Add "active" class when you're on that page" -->
          <a class="nav-link active" href="">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="">
            <i class="ion-compose"></i>&nbsp;New Post
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="">
            <i class="ion-gear-a"></i>&nbsp;Settings
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="">Sign up</a>
        </li>
      </ul>
    </div>
  </nav>
</template>
